//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from CanvasStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class CanvasStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.CanvasStrings", typeof(CanvasStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Canvas_AdvancedSmoothing => ResourceManager.GetString(nameof(Canvas_AdvancedSmoothing), _resourceCulture);

        public static string Canvas_AskEachTime => ResourceManager.GetString(nameof(Canvas_AskEachTime), _resourceCulture);

        public static string Canvas_AutoRestoreTimePoints => ResourceManager.GetString(nameof(Canvas_AutoRestoreTimePoints), _resourceCulture);

        public static string Canvas_BrushAutoRestore => ResourceManager.GetString(nameof(Canvas_BrushAutoRestore), _resourceCulture);

        public static string Canvas_BrushAutoRestoreHint => ResourceManager.GetString(nameof(Canvas_BrushAutoRestoreHint), _resourceCulture);

        public static string Canvas_ClearCanvasAlsoClearImages => ResourceManager.GetString(nameof(Canvas_ClearCanvasAlsoClearImages), _resourceCulture);

        public static string Canvas_ClearInkAlsoClearHistory => ResourceManager.GetString(nameof(Canvas_ClearInkAlsoClearHistory), _resourceCulture);

        public static string Canvas_Color_Black => ResourceManager.GetString(nameof(Canvas_Color_Black), _resourceCulture);

        public static string Canvas_Color_Blue => ResourceManager.GetString(nameof(Canvas_Color_Blue), _resourceCulture);

        public static string Canvas_Color_Default => ResourceManager.GetString(nameof(Canvas_Color_Default), _resourceCulture);

        public static string Canvas_Color_Green => ResourceManager.GetString(nameof(Canvas_Color_Green), _resourceCulture);

        public static string Canvas_Color_Orange => ResourceManager.GetString(nameof(Canvas_Color_Orange), _resourceCulture);

        public static string Canvas_Color_Purple => ResourceManager.GetString(nameof(Canvas_Color_Purple), _resourceCulture);

        public static string Canvas_Color_Red => ResourceManager.GetString(nameof(Canvas_Color_Red), _resourceCulture);

        public static string Canvas_Color_White => ResourceManager.GetString(nameof(Canvas_Color_White), _resourceCulture);

        public static string Canvas_Color_Yellow => ResourceManager.GetString(nameof(Canvas_Color_Yellow), _resourceCulture);

        public static string Canvas_CompressPicturesUploaded => ResourceManager.GetString(nameof(Canvas_CompressPicturesUploaded), _resourceCulture);

        public static string Canvas_CurveSmoothing_Off => ResourceManager.GetString(nameof(Canvas_CurveSmoothing_Off), _resourceCulture);

        public static string Canvas_CurveSmoothingMode => ResourceManager.GetString(nameof(Canvas_CurveSmoothingMode), _resourceCulture);

        public static string Canvas_DisableHardwareAcceleration => ResourceManager.GetString(nameof(Canvas_DisableHardwareAcceleration), _resourceCulture);

        public static string Canvas_DisableHardwareAccelerationHint => ResourceManager.GetString(nameof(Canvas_DisableHardwareAccelerationHint), _resourceCulture);

        public static string Canvas_DisablePressureHint => ResourceManager.GetString(nameof(Canvas_DisablePressureHint), _resourceCulture);

        public static string Canvas_EnablePressureTouch => ResourceManager.GetString(nameof(Canvas_EnablePressureTouch), _resourceCulture);

        public static string Canvas_EnablePressureTouchHint => ResourceManager.GetString(nameof(Canvas_EnablePressureTouchHint), _resourceCulture);

        public static string Canvas_EraserSize => ResourceManager.GetString(nameof(Canvas_EraserSize), _resourceCulture);

        public static string Canvas_EraserSize_Large => ResourceManager.GetString(nameof(Canvas_EraserSize_Large), _resourceCulture);

        public static string Canvas_EraserSize_Medium => ResourceManager.GetString(nameof(Canvas_EraserSize_Medium), _resourceCulture);

        public static string Canvas_EraserSize_Small => ResourceManager.GetString(nameof(Canvas_EraserSize_Small), _resourceCulture);

        public static string Canvas_EraserSize_VeryLarge => ResourceManager.GetString(nameof(Canvas_EraserSize_VeryLarge), _resourceCulture);

        public static string Canvas_EraserSize_VerySmall => ResourceManager.GetString(nameof(Canvas_EraserSize_VerySmall), _resourceCulture);

        public static string Canvas_EraserSizeHint => ResourceManager.GetString(nameof(Canvas_EraserSizeHint), _resourceCulture);

        public static string Canvas_GroupTitle => ResourceManager.GetString(nameof(Canvas_GroupTitle), _resourceCulture);

        public static string Canvas_HideInkOnExit => ResourceManager.GetString(nameof(Canvas_HideInkOnExit), _resourceCulture);

        public static string Canvas_HideStrokeWhenSelectingHint => ResourceManager.GetString(nameof(Canvas_HideStrokeWhenSelectingHint), _resourceCulture);

        public static string Canvas_HyperbolaAsymptoteHint => ResourceManager.GetString(nameof(Canvas_HyperbolaAsymptoteHint), _resourceCulture);

        public static string Canvas_IgnorePressure => ResourceManager.GetString(nameof(Canvas_IgnorePressure), _resourceCulture);

        public static string Canvas_KeepAsymptote => ResourceManager.GetString(nameof(Canvas_KeepAsymptote), _resourceCulture);

        public static string Canvas_LaunchSeewoVideoShowcaseForWhiteboardBooth => ResourceManager.GetString(nameof(Canvas_LaunchSeewoVideoShowcaseForWhiteboardBooth), _resourceCulture);

        public static string Canvas_LaunchSeewoVideoShowcaseForWhiteboardBoothHint => ResourceManager.GetString(nameof(Canvas_LaunchSeewoVideoShowcaseForWhiteboardBoothHint), _resourceCulture);

        public static string Canvas_MergeInkSmoothingWithUndo => ResourceManager.GetString(nameof(Canvas_MergeInkSmoothingWithUndo), _resourceCulture);

        public static string Canvas_MergeInkSmoothingWithUndoHint => ResourceManager.GetString(nameof(Canvas_MergeInkSmoothingWithUndoHint), _resourceCulture);

        public static string Canvas_No => ResourceManager.GetString(nameof(Canvas_No), _resourceCulture);

        public static string Canvas_RestoreColor => ResourceManager.GetString(nameof(Canvas_RestoreColor), _resourceCulture);

        public static string Canvas_RestoreOpacity => ResourceManager.GetString(nameof(Canvas_RestoreOpacity), _resourceCulture);

        public static string Canvas_RestoreWidth => ResourceManager.GetString(nameof(Canvas_RestoreWidth), _resourceCulture);

        public static string Canvas_ShowCircleCenter => ResourceManager.GetString(nameof(Canvas_ShowCircleCenter), _resourceCulture);

        public static string Canvas_ShowCoordinateUnitMarks => ResourceManager.GetString(nameof(Canvas_ShowCoordinateUnitMarks), _resourceCulture);

        public static string Canvas_ShowCoordinateUnitMarksHint => ResourceManager.GetString(nameof(Canvas_ShowCoordinateUnitMarksHint), _resourceCulture);

        public static string Canvas_ShowPenCursor => ResourceManager.GetString(nameof(Canvas_ShowPenCursor), _resourceCulture);

        public static string Canvas_PenCursorType => ResourceManager.GetString(nameof(Canvas_PenCursorType), _resourceCulture);

        public static string Canvas_PenCursorTypeHint => ResourceManager.GetString(nameof(Canvas_PenCursorTypeHint), _resourceCulture);

        public static string Canvas_PenCursorType_System => ResourceManager.GetString(nameof(Canvas_PenCursorType_System), _resourceCulture);

        public static string Canvas_PenCursorType_BuiltIn => ResourceManager.GetString(nameof(Canvas_PenCursorType_BuiltIn), _resourceCulture);

        public static string Canvas_PenCursorType_Custom => ResourceManager.GetString(nameof(Canvas_PenCursorType_Custom), _resourceCulture);

        public static string Canvas_CustomPenCursorPath => ResourceManager.GetString(nameof(Canvas_CustomPenCursorPath), _resourceCulture);

        public static string Canvas_CustomPenCursorPathHint => ResourceManager.GetString(nameof(Canvas_CustomPenCursorPathHint), _resourceCulture);

        public static string Canvas_SelectCustomPenCursor => ResourceManager.GetString(nameof(Canvas_SelectCustomPenCursor), _resourceCulture);

        public static string Canvas_CustomPenCursorFilter => ResourceManager.GetString(nameof(Canvas_CustomPenCursorFilter), _resourceCulture);

        public static string Canvas_SwitchBackAfterEraser => ResourceManager.GetString(nameof(Canvas_SwitchBackAfterEraser), _resourceCulture);

        public static string Canvas_SwitchBackAfterEraserHint => ResourceManager.GetString(nameof(Canvas_SwitchBackAfterEraserHint), _resourceCulture);

        public static string Canvas_SwitchBackDelay => ResourceManager.GetString(nameof(Canvas_SwitchBackDelay), _resourceCulture);

        public static string Canvas_SwitchBackDelayHint => ResourceManager.GetString(nameof(Canvas_SwitchBackDelayHint), _resourceCulture);

        public static string Canvas_UseLegacyInkSystem => ResourceManager.GetString(nameof(Canvas_UseLegacyInkSystem), _resourceCulture);

        public static string Canvas_UseLegacyInkSystemHint => ResourceManager.GetString(nameof(Canvas_UseLegacyInkSystemHint), _resourceCulture);

        public static string Canvas_UseLegacyInkSystemRestartNotice => ResourceManager.GetString(nameof(Canvas_UseLegacyInkSystemRestartNotice), _resourceCulture);

        public static string Canvas_WPFBezier => ResourceManager.GetString(nameof(Canvas_WPFBezier), _resourceCulture);

        public static string Canvas_Yes => ResourceManager.GetString(nameof(Canvas_Yes), _resourceCulture);

        public static string CanvasAndInkPanel_1920_1080Hint => ResourceManager.GetString("CanvasAndInkPanel_1920×1080Hint", _resourceCulture);

        public static string CanvasAndInkPanel_Hint_9 => ResourceManager.GetString(nameof(CanvasAndInkPanel_Hint_9), _resourceCulture);

        public static string InkRecog_AutoStraightLine => ResourceManager.GetString(nameof(InkRecog_AutoStraightLine), _resourceCulture);

        public static string InkRecog_BlockRectFakePressure => ResourceManager.GetString(nameof(InkRecog_BlockRectFakePressure), _resourceCulture);

        public static string InkRecog_BlockTriFakePressure => ResourceManager.GetString(nameof(InkRecog_BlockTriFakePressure), _resourceCulture);

        public static string InkRecog_EnableInkRecognition => ResourceManager.GetString(nameof(InkRecog_EnableInkRecognition), _resourceCulture);

        public static string InkRecog_FixEllipse => ResourceManager.GetString(nameof(InkRecog_FixEllipse), _resourceCulture);

        public static string InkRecog_FixRectangle => ResourceManager.GetString(nameof(InkRecog_FixRectangle), _resourceCulture);

        public static string InkRecog_FixTriangle => ResourceManager.GetString(nameof(InkRecog_FixTriangle), _resourceCulture);

        public static string InkRecog_HandwritingBeautify => ResourceManager.GetString(nameof(InkRecog_HandwritingBeautify), _resourceCulture);

        public static string InkRecog_HandwritingBeautifyHint => ResourceManager.GetString(nameof(InkRecog_HandwritingBeautifyHint), _resourceCulture);

        public static string InkRecog_HandwritingFont => ResourceManager.GetString(nameof(InkRecog_HandwritingFont), _resourceCulture);

        public static string InkRecog_HandwritingFontHint => ResourceManager.GetString(nameof(InkRecog_HandwritingFontHint), _resourceCulture);

        public static string InkRecog_HighPrecisionHint => ResourceManager.GetString(nameof(InkRecog_HighPrecisionHint), _resourceCulture);

        public static string InkRecog_HighPrecisionStraighten => ResourceManager.GetString(nameof(InkRecog_HighPrecisionStraighten), _resourceCulture);

        public static string InkRecog_LengthThreshold => ResourceManager.GetString(nameof(InkRecog_LengthThreshold), _resourceCulture);

        public static string InkRecog_LineEndpointSnapping => ResourceManager.GetString(nameof(InkRecog_LineEndpointSnapping), _resourceCulture);

        public static string InkRecog_LineEndpointSnappingHint => ResourceManager.GetString(nameof(InkRecog_LineEndpointSnappingHint), _resourceCulture);

        public static string InkRecog_PauseStraightenDelay => ResourceManager.GetString(nameof(InkRecog_PauseStraightenDelay), _resourceCulture);

        public static string InkRecog_PauseStraightenHint => ResourceManager.GetString(nameof(InkRecog_PauseStraightenHint), _resourceCulture);

        public static string InkRecog_PauseStraightenLine => ResourceManager.GetString(nameof(InkRecog_PauseStraightenLine), _resourceCulture);

        public static string InkRecog_Sensitivity => ResourceManager.GetString(nameof(InkRecog_Sensitivity), _resourceCulture);

        public static string InkRecog_ShapeEngine => ResourceManager.GetString(nameof(InkRecog_ShapeEngine), _resourceCulture);

        public static string InkRecog_ShapeEngineAuto => ResourceManager.GetString(nameof(InkRecog_ShapeEngineAuto), _resourceCulture);

        public static string InkRecog_ShapeEngineHint => ResourceManager.GetString(nameof(InkRecog_ShapeEngineHint), _resourceCulture);

        public static string InkRecog_SnappingDistance => ResourceManager.GetString(nameof(InkRecog_SnappingDistance), _resourceCulture);

        public static string InkRecog_Title => ResourceManager.GetString(nameof(InkRecog_Title), _resourceCulture);

        public static string InkRecog_Font_InkFreeKaiti => ResourceManager.GetString(nameof(InkRecog_Font_InkFreeKaiti), _resourceCulture);

        public static string InkRecog_Font_Kaiti => ResourceManager.GetString(nameof(InkRecog_Font_Kaiti), _resourceCulture);

        public static string InkRecog_Font_STKaiti => ResourceManager.GetString(nameof(InkRecog_Font_STKaiti), _resourceCulture);

        public static string InkRecog_Font_STXingkai => ResourceManager.GetString(nameof(InkRecog_Font_STXingkai), _resourceCulture);

        public static string InkRecog_Font_FangSong => ResourceManager.GetString(nameof(InkRecog_Font_FangSong), _resourceCulture);

        public static string InkRecog_Font_STFangsong => ResourceManager.GetString(nameof(InkRecog_Font_STFangsong), _resourceCulture);

        public static string InkRecog_Font_LiSu => ResourceManager.GetString(nameof(InkRecog_Font_LiSu), _resourceCulture);

        public static string InkRecog_Font_YouYuan => ResourceManager.GetString(nameof(InkRecog_Font_YouYuan), _resourceCulture);

        public static string InkRecog_ShapeCorrection => ResourceManager.GetString(nameof(InkRecog_ShapeCorrection), _resourceCulture);

        public static string Canvas_SecondsFormat => ResourceManager.GetString(nameof(Canvas_SecondsFormat), _resourceCulture);

        public static string Canvas_BackgroundSettings => ResourceManager.GetString(nameof(Canvas_BackgroundSettings), _resourceCulture);

        public static string Canvas_WhiteboardMode => ResourceManager.GetString(nameof(Canvas_WhiteboardMode), _resourceCulture);

        public static string Canvas_Blackboard => ResourceManager.GetString(nameof(Canvas_Blackboard), _resourceCulture);

        public static string Canvas_BackgroundColor => ResourceManager.GetString(nameof(Canvas_BackgroundColor), _resourceCulture);

        public static string Canvas_ApplyColor => ResourceManager.GetString(nameof(Canvas_ApplyColor), _resourceCulture);

        public static string Canvas_DarkMode => ResourceManager.GetString(nameof(Canvas_DarkMode), _resourceCulture);

        public static string Shape_RemoveAsymptote => ResourceManager.GetString(nameof(Shape_RemoveAsymptote), _resourceCulture);
    }
}